# Generated by Django 4.1.4 on 2022-12-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profilemodel_batch_profilemodel_batch_fee_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profilemodel",
            name="batch_fee",
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="batch_slots",
            field=models.IntegerField(
                choices=[(1, "6-7AM"), (2, "7-8AM"), (3, "8-9AM"), (4, "5-6PM")],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="profilemodel",
            name="batchmonth",
            field=models.CharField(
                choices=[
                    ("DEC", "December"),
                    ("JAN", "January"),
                    ("FEB", "February"),
                    ("MAR", "March"),
                    ("APR", "April"),
                    ("MAY", "May"),
                    ("JUN", "June"),
                    ("JUL", "July"),
                    ("AUG", "August"),
                    ("SEP", "September"),
                    ("OCT", "October"),
                    ("NOV", "November"),
                ],
                default="N/A",
                max_length=3,
            ),
        ),
    ]
