# Generated by Django 4.1.4 on 2022-12-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BatchesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_slots",
                    models.IntegerField(
                        choices=[(1, "One"), (2, "Two"), (3, "Three"), (4, "Four")]
                    ),
                ),
                ("batch_fee", models.IntegerField(default=500, editable=False)),
                (
                    "batch_month",
                    models.IntegerField(
                        choices=[
                            (1, "Jan"),
                            (2, "Feb"),
                            (3, "Mar"),
                            (4, "Apr"),
                            (5, "May"),
                            (6, "Jun"),
                            (7, "Jul"),
                            (8, "Aug"),
                            (9, "Sep"),
                            (10, "Oct"),
                            (11, "Nov"),
                            (12, "Dec"),
                        ]
                    ),
                ),
            ],
        ),
    ]
