# Generated by Django 4.1.4 on 2022-12-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batches", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchesmodel",
            name="id",
        ),
        migrations.AddField(
            model_name="batchesmodel",
            name="batch_id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="batchesmodel",
            name="batch_slots",
            field=models.IntegerField(
                choices=[(1, "One"), (2, "Two"), (3, "Three"), (4, "Four")], unique=True
            ),
        ),
    ]
