# Generated by Django 4.1.4 on 2022-12-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_profilemodel_batch_profilemodel_batch_fee_and_more"),
        ("batches", "0002_remove_batchesmodel_id_batchesmodel_batch_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BatchesModel",
        ),
    ]
